baseURL = "http://docs.groupdocs.com/"
languageCode = "en-us"
title = "Documentation"
theme = "hugo-book"


# (Optional) Set this to true to enable 'Last Modified by' date and git author
#  information on 'doc' type pages.
enableGitInfo = true

# Markup configure section
# See https://gohugo.io/getting-started/configuration-markup/
[markup]
    defaultMarkdownHandler = "goldmark"
    [markup.goldmark.renderer]
        unsafe= true
    [markup.tableOfContents]
        startLevel = 2
        endLevel = 4
        ordered = false


[params]
    contentDir = "content"
    # Set source repository location.
    # Used for 'Last Modified' and 'Edit this page' links.
    BookRepo = 'https://github.com/groupdocs/docs'
    
    # Enable 'Edit this page' links for 'doc' page type.
    # Disabled by default. Uncomment to enable. Requires 'BookRepo' param.    
    BookEditPath = 'edit/master'    #https://github.com/groupdocs/docs/blob/master/content/docs/annotation-net/getting-started/supported-document-formats.md
                                     
        
       

        
  
