# Build documentation

name: build and deploy

# Controls when the workflow will run
on:
  # Run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Hugo
        run: |
          curl -LO https://github.com/gohugoio/hugo/releases/download/v0.101.0/hugo_extended_0.101.0_Linux-64bit.deb
          sudo dpkg -i hugo_extended_0.101.0_Linux-64bit.deb
          
      - name: Build site
        run: |
          hugo --minify --config config-geekdoc.toml,ignore-total-config.toml

